### ISSUE TITLE
ApacheWire null body

### ISSUE THREAD

**Issue by VidakovicDominik** [Vatavuk/verano-http#41]
ApacheWire does not check if the response contains a body before fetching it.

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.31`

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.31`

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.31`

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.31`

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.31`

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.31`

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.41`

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.41`

**Comment by Vatavuk** [comment]
@rultor release, tag is `0.41`
